# Generated by Django 3.2.7 on 2021-10-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ansto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_question', to='api.answer'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
