# Generated by Django 3.2.7 on 2021-10-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_ansto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ansto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment', to='api.comment'),
        ),
    ]
